Add docker-compose to startup script; minor refactor

diff --git a/script/start b/script/start
--- a/script/start
+++ b/script/start
@@ -1,16 +1,5 @@
 #!/bin/bash -e
 
-STATUS=$(aws sts get-caller-identity --profile composer 2>&1 || true)
-if [[ ${STATUS} =~ (ExpiredToken) ]]; then
-  echo -e "${red}Credentials for the composer profile are expired. Please fetch new credentials and run this again.${plain}"
-  exit 1
-elif [[ ${STATUS} =~ ("could not be found") ]]; then
-  echo -e "${red}Credentials for the composer profile are missing. Please ensure you have the right credentials.${plain}"
-  exit 1
-fi
-
-(cd rule-manager/rule-manager-client && npm i && npm run start)
-
 IS_DEBUG=false
 for arg in "$@"
 do
@@ -20,8 +9,35 @@ do
   fi
 done
 
-if [[ "$IS_DEBUG" = true ]] ; then
-  sbt -jvm-debug 5005 run
-else
-  sbt "checker / run"
-fi
+function checkCredentials {
+  STATUS=$(aws sts get-caller-identity --profile composer 2>&1 || true)
+  if [[ ${STATUS} =~ (ExpiredToken) ]]; then
+    echo -e "${red}Credentials for the composer profile are expired. Please fetch new credentials and run this again.${plain}"
+    exit 1
+  elif [[ ${STATUS} =~ ("could not be found") ]]; then
+    echo -e "${red}Credentials for the composer profile are missing. Please ensure you have the right credentials.${plain}"
+    exit 1
+  fi
+}
+
+function setupDependencies {
+  docker-compose up -d
+  (cd rule-manager/rule-manager-client && npm i && npm run start)
+}
+
+function teardownDependencies {
+  docker-compose down
+}
+
+function runApp {
+  if [[ "$IS_DEBUG" = true ]] ; then
+    sbt -jvm-debug 5005 run
+  else
+    sbt "checker / run"
+  fi
+}
+
+trap teardownDependencies EXIT
+
+setupDependencies
+runApp
